"""Remove monitoring_enabled field

Revision ID: 193add0fe31b
Revises: 
Create Date: 2025-09-07 12:37:16.065917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193add0fe31b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('monitoring_enabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitoring_enabled', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
